<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ7S47go\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ7S47go/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ7S47go.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQ7S47go\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQ7S47go\appAppKernelProdContainer([
    'container.build_hash' => 'Q7S47go',
    'container.build_id' => '4c8e2e2f',
    'container.build_time' => 1720436845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ7S47go');
